spring.application.name=RelatorioAniversariantes

# Credenciais para o login no sistema Church
app.credentials.client-code=19700
app.credentials.username=Cila
app.credentials.password=Ad46crente

# --- CONFIGURAÇÕES DO WHATSAPP (EVOLUTION API) ---
whatsapp.api.url=http://localhost:8081/message/sendMedia/igreja
whatsapp.api.key=SUA_CHAVE_SUPER_SECRETA_AQUI
# Número do destinatário (Código do país + DDD + Número)
whatsapp.destinatario=5585982317976

# --- CONFIGURAÇÕES DE RELATÓRIOS ---
app.reports.output-directory=relatorios
app.reports.retention-days=30